### PR TITLE
Upgrade terraform-provider-linode to v2.2.0

### LINKED ISSUE #267: Upgrade terraform-provider-linode to v2.1.0
Release details: https://github.com/linode/terraform-provider-linode/releases/tag/v2.1.0

### LINKED ISSUE #270: Upgrade terraform-provider-linode to v2.1.1
Release details: https://github.com/linode/terraform-provider-linode/releases/tag/v2.1.1

### LINKED ISSUE #274: Upgrade terraform-provider-linode to v2.2.0
Release details: https://github.com/linode/terraform-provider-linode/releases/tag/v2.2.0

### PR DESCRIPTION
**Pull request by iwahbe**
This PR incorporates the PF based resources into the provider.

This PR was generated via `$ upgrade-provider pulumi/pulumi-linode --upstream-provider-name=terraform-provider-linode --pulumi-infer-version=true`.

---

- Upgrading terraform-provider-linode from 2.0.0  to 2.2.0.
	Fixes #274
	Fixes #270
	Fixes #267
- Upgrading pulumi-terraform-bridge from v3.44.3 to v3.47.2.

### CODE REVIEW

**Review by aq17 — APPROVED** [review]

**Comment by iwahbe** [comment]
@aq17 Did you match our breaking changes with upstream? I couldn't so if you did that would be great.

**Comment by aq17** [comment]
@iwahbe the missing resource/ function `databaseMongodb` looks correct, but it appears `stackScript` still contains the attribute `userDefinedFields` https://github.com/linode/terraform-provider-linode/blob/dev/linode/stackscript/framework_resource_schema.go#L122

Looks like [a PR was just merged](https://github.com/linode/terraform-provider-linode/pull/827) to resolve some issues with the migration, so will hold off on merging this and wait for the next upstream version release

cc @t0yv0 on ops

**Comment by t0yv0** [comment]
Ack, thank you.

**Comment by t0yv0** [comment]
@aq17 looking at this again, it seems that https://github.com/linode/terraform-provider-linode/releases/tag/v2.2.0 already includes the referenced fix for upstream 227 issue. Can you clarify what upstream issue we need to wait on or what is the blocker here?

Looking closely at missing userDefinedFields this may be an issue with our tfgen recognizing list-of-object attributes, let me have a closer look. Perhaps if we can fix that we can go forward.

**Comment by t0yv0** [comment]
Yeah I think it's a blocker, originating in a likely bug in pulumi-terraform-bridge; will dig in shortly.

**Comment by t0yv0** [comment]
```
jq '.resources["linode:index/stackScript:StackScript"].inputProperties|keys' provider/cmd/pulumi-resource-linode/schema.json                                                  ~/code/pulumi-linode
[
  "description",
  "images",
  "isPublic",
  "label",
  "revNote",
  "script"
]
t0yv0@Antons-MacBook-Pro> jq '.resources["linode:index/stackScript:StackScript"].properties|keys' provider/cmd/pulumi-resource-linode/schema.json                                                       ~/code/pulumi-linode
[
  "created",
  "deploymentsActive",
  "deploymentsTotal",
  "description",
  "images",
  "isPublic",
  "label",
  "revNote",
  "script",
  "updated",
  "userDefinedFields",
  "userGravatarId",
  "username"
]
```

So on second look it looks like it's working as expected. 

Upstream field is marked Computed. This means it's always set by the provider and ignores user input. Bridge maps that to an output property but not an input property. 

```
		"user_defined_fields": schema.ListAttribute{
			Description: "This is a list of fields defined with a special syntax inside this " +
				"StackScript that allow for supplying customized parameters during deployment.",
			Computed:    true,
			ElementType: udfObjectType,
		},
```

**Comment by t0yv0** [comment]
Here's the change: https://github.com/linode/terraform-provider-linode/commit/d47b869cfc34121e9de2b6f5e354fbfa7106ecbd#diff-5af75137b7aae5257e45b292214d3df63f67baa252fcb900de8e663727a515f4L77

It used to be Computed+Optional upstream meaning that it used to be overridable from the user program. It is no longer. I think this explains the breaking change.

Are we good to go here @aq17 or any other concerns?

**Comment by t0yv0** [comment]
https://github.com/linode/terraform-provider-linode/pull/804 MongoDB removal

**Comment by aq17** [comment]
> Here's the change: [linode/terraform-provider-linode@d47b869#diff-5af75137b7aae5257e45b292214d3df63f67baa252fcb900de8e663727a515f4L77](https://github.com/linode/terraform-provider-linode/commit/d47b869cfc34121e9de2b6f5e354fbfa7106ecbd#diff-5af75137b7aae5257e45b292214d3df63f67baa252fcb900de8e663727a515f4L77)
> 
> It used to be Computed+Optional upstream meaning that it used to be overridable from the user program. It is no longer. I think this explains the breaking change.
> 
> Are we good to go here @aq17 or any other concerns?

@t0yv0 that makes sense, think it's good 👍🏼

**Pull request merged**
