### PR TITLE
Use patch instead of fork

### PR DESCRIPTION
**Pull request by aq17**

### CODE REVIEW

**Comment by aq17** [comment]
I'm not fully sure why there are schema changes here, as [this commit ](https://github.com/pulumi/pulumi-linode/commit/1146e90ab6169cb9928d9dfdba16ee26e79fd19a#diff-6df35dbe33e0cfc87d24681230344fd93e0fce876747040427455c491c8a0d68) already updated to `1.30.0`.

**Review by AaronFriel — COMMENTED** [review]
I see schema changes, no SDK changes. Something is amiss.

**Review by iwahbe — COMMENTED** [review]
It looks like the `upstream` module is pointed to the current head of the upstream repo [`76b55f`](https://github.com/linode/terraform-provider-linode/tree/76b55f46c00989b6490554a904f4d0ffa0d06c1d). It should be pointed to the tag we are tracking: [`1.30.0`](https://github.com/linode/terraform-provider-linode/releases/tag/v1.30.0).

We should do patch updates on up to date repos. This way any diff in `sdk/` or `schema.json` is a clear sign that something went wrong with the update.

**Review by AaronFriel — COMMENTED** [review]
@aq17 can you checkout master or `rm -rf sdk/*/*` (that should keep go.mod and go.sum intact)?

When we generate new resources & functions, they aren't cleaned up by rebuilding SDKs. Something we might want to fix.

**Comment by aq17** [comment]
Closing in favor of https://github.com/pulumi/pulumi-linode/pull/239.

**Pull request closed without merging**
